# Generated by Django 2.0.3 on 2020-06-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta',
            name='name',
            field=models.CharField(default='teste', max_length=64),
        ),
        migrations.AddField(
            model_name='pasta',
            name='price',
            field=models.FloatField(default='0'),
        ),
    ]
