# Generated by Django 2.0.3 on 2020-06-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200618_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='teste', max_length=64)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='salad',
            old_name='print',
            new_name='price',
        ),
    ]
