# Generated by Django 2.0.3 on 2020-06-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200618_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plater',
            old_name='price',
            new_name='price1',
        ),
        migrations.AddField(
            model_name='plater',
            name='price2',
            field=models.FloatField(default=0),
        ),
    ]
