# Generated by Django 2.0.3 on 2020-06-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='name',
            field=models.CharField(default='teste', max_length=64),
        ),
    ]
