# Generated by Django 2.0.3 on 2020-06-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_topping_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regular_pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='teste', max_length=64)),
                ('price1', models.FloatField(default=0)),
                ('price2', models.FloatField(default=0)),
                ('option', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sicillia_pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='teste', max_length=64)),
                ('price1', models.FloatField(default=0)),
                ('price2', models.FloatField(default=0)),
                ('option', models.IntegerField(default=0)),
            ],
        ),
    ]
