# Generated by Django 2.0.3 on 2020-06-22 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0009_subs'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_reg_pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='teste', max_length=64)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Regular_pizza')),
                ('option_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppiqqerng1', to='orders.Topping')),
                ('option_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping2', to='orders.Topping')),
                ('option_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppifaerwng3', to='orders.Topping')),
                ('option_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppdafweing4', to='orders.Topping')),
                ('option_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topdfasfping5', to='orders.Topping')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_sici_pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='teste', max_length=64)),
                ('fifth_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppifadsfaang5', to='orders.Topping')),
                ('first_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adfa', to='orders.Topping')),
                ('forth_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppierqsng4', to='orders.Topping')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_id', to='orders.Regular_pizza')),
                ('second_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fasfae', to='orders.Topping')),
                ('third_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slfkgs', to='orders.Topping')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
