# Generated by Django 2.0.3 on 2020-06-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200623_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_sici_pizza',
            name='fifth_option',
        ),
        migrations.RemoveField(
            model_name='user_sici_pizza',
            name='first_option',
        ),
        migrations.RemoveField(
            model_name='user_sici_pizza',
            name='forth_option',
        ),
        migrations.RemoveField(
            model_name='user_sici_pizza',
            name='second_option',
        ),
        migrations.RemoveField(
            model_name='user_sici_pizza',
            name='third_option',
        ),
        migrations.AddField(
            model_name='user_sici_pizza',
            name='option_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_sici_pizza',
            name='option_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_sici_pizza',
            name='option_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_sici_pizza',
            name='option_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_sici_pizza',
            name='option_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_sici_pizza',
            name='item_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_sici_pizza',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
