# Generated by Django 2.0.3 on 2020-06-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200623_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('item_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user_plater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('item_id', models.IntegerField(default=0)),
                ('size', models.CharField(default='teste', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='user_salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('item_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('item_id', models.IntegerField(default=0)),
                ('size', models.CharField(default='teste', max_length=64)),
            ],
        ),
    ]
