# Generated by Django 2.0.3 on 2020-06-24 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_user_pasta_user_plater_user_salad_user_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_pasta',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='orders.Pasta'),
        ),
    ]
