# Generated by Django 2.0.3 on 2020-06-25 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200625_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg_pizza',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='orders.Regular_pizza'),
        ),
        migrations.AlterField(
            model_name='user_reg_pizza',
            name='option_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_added_1_r', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='user_reg_pizza',
            name='option_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_added_2_r', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='user_reg_pizza',
            name='option_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_added_3_r', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='user_reg_pizza',
            name='option_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_added_4_r', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='user_reg_pizza',
            name='option_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_added_5_r', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='user_reg_pizza',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_pizza_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_sici_pizza',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='orders.Sicillia_pizza'),
        ),
        migrations.AlterField(
            model_name='user_sici_pizza',
            name='option_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_added_1', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='user_sici_pizza',
            name='option_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_added_2', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='user_sici_pizza',
            name='option_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_added_3', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='user_sici_pizza',
            name='option_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_added_4', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='user_sici_pizza',
            name='option_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_added_5', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='user_sici_pizza',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sici_pizza_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
