# Generated by Django 2.0.3 on 2020-06-25 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200625_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_reg_pizza',
            name='option_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping1', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='user_reg_pizza',
            name='option_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping2', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='user_reg_pizza',
            name='option_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping3', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='user_reg_pizza',
            name='option_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping4', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='user_reg_pizza',
            name='option_5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping5', to='orders.Topping'),
        ),
    ]
