# Generated by Django 2.0.3 on 2020-06-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_user_reg_pizza_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_pasta',
            name='confirm',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user_plater',
            name='confirm',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user_salad',
            name='confirm',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user_sici_pizza',
            name='confirm',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='user_sub',
            name='confirm',
            field=models.BooleanField(default=0),
        ),
    ]
